package com.zizazr.kjsgen.integration.kubejs;

import com.zizazr.kjsgen.KjsGen;
import com.zizazr.kjsgen.core.ProjectManager;
import com.zizazr.kjsgen.core.RecipeInstance;
import com.zizazr.kjsgen.core.RecipeProject;
import dev.architectury.platform.Platform;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Writes assembled scripts into {@code <game dir>/kubejs/server_scripts/}.
 *
 * Every export block is wrapped in marker comments
 * {@code // kjsgen:start <id>} / {@code // kjsgen:end <id>}; re-exporting
 * replaces only the marked block, so manual edits elsewhere in the file
 * survive. All writes are confined to the kubejs directory of the current
 * instance.
 */
public final class KubeJsExporter {
    public static final String MARKER_START = "// kjsgen:start ";
    public static final String MARKER_END = "// kjsgen:end ";

    public record FileResult(String fileName, Path path, int recipeCount, boolean created) {
    }

    public record ExportResult(List<FileResult> files, List<String> warnings) {
    }

    private KubeJsExporter() {
    }

    public static Path serverScriptsDir() {
        return Platform.getGameFolder().resolve("kubejs").resolve("server_scripts");
    }

    /** File-name-safe script name without extension. */
    public static String sanitizeFileName(String name) {
        String cleaned = name.trim()
                .replaceAll("\\.js$", "")
                .replaceAll("[^A-Za-z0-9_\\-]", "_");
        return cleaned.isEmpty() ? "kjsgen_recipes" : cleaned;
    }

    /**
     * Resolves a script file strictly inside {@code kubejs/server_scripts}.
     *
     * @throws IOException when the resolved path would escape the directory
     */
    public static Path resolveScriptFile(String fileName) throws IOException {
        Path base = serverScriptsDir().toAbsolutePath().normalize();
        Path resolved = base.resolve(sanitizeFileName(fileName) + ".js").normalize();
        if (!resolved.startsWith(base)) {
            throw new IOException("Refusing to write outside kubejs/server_scripts: " + resolved);
        }
        return resolved;
    }

    /** Export the whole project, one file per target file group. */
    public static ExportResult exportProject(RecipeProject project) throws IOException {
        List<FileResult> results = new ArrayList<>();
        List<String> warnings = new ArrayList<>();
        if (!KjsGen.isKubeJsLoaded()) {
            warnings.add("kjsgen.export.warn_no_kubejs");
        }
        for (Map.Entry<String, List<RecipeInstance>> entry : project.recipesByTargetFile().entrySet()) {
            results.add(exportToFile(project, entry.getKey(), entry.getValue()));
        }
        return new ExportResult(results, warnings);
    }

    /** Export one group of recipes into one script file, merging by markers. */
    public static FileResult exportToFile(RecipeProject project, String fileName, List<RecipeInstance> recipes) throws IOException {
        Path file = resolveScriptFile(fileName);
        Files.createDirectories(file.getParent());

        String blockId = ProjectManager.sanitizeName(project.name());
        String block = MARKER_START + blockId + "\n"
                + "// Generated by KubeJS Generator (kjsgen) from project '" + project.name() + "'.\n"
                + "// Everything inside this marker block is overwritten on re-export; edits outside it are kept.\n"
                + ScriptAssembler.assemble(project, recipes)
                + MARKER_END + blockId + "\n";

        boolean created = !Files.isRegularFile(file);
        String content;
        if (created) {
            content = block;
        } else {
            content = mergeBlock(Files.readString(file, StandardCharsets.UTF_8), blockId, block);
        }
        Files.writeString(file, content, StandardCharsets.UTF_8);
        KjsGen.LOGGER.info("kjsgen exported {} recipes to {}", recipes.size(), file);
        return new FileResult(sanitizeFileName(fileName), file, recipes.size(), created);
    }

    /**
     * Replaces the marker block with id {@code blockId} inside {@code existing},
     * or appends the block at the end when no markers are present.
     */
    static String mergeBlock(String existing, String blockId, String block) {
        String startMarker = MARKER_START + blockId;
        String endMarker = MARKER_END + blockId;
        String[] lines = existing.split("\n", -1);
        int startLine = -1;
        int endLine = -1;
        for (int i = 0; i < lines.length; i++) {
            String trimmed = lines[i].trim();
            if (startLine < 0 && trimmed.equals(startMarker)) {
                startLine = i;
            } else if (startLine >= 0 && trimmed.equals(endMarker)) {
                endLine = i;
                break;
            }
        }
        if (startLine < 0 || endLine < 0) {
            // no (complete) block yet: append at the end
            StringBuilder sb = new StringBuilder(existing);
            if (!existing.endsWith("\n")) {
                sb.append("\n");
            }
            if (!existing.isBlank()) {
                sb.append("\n");
            }
            sb.append(block);
            return sb.toString();
        }
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < startLine; i++) {
            sb.append(lines[i]).append("\n");
        }
        sb.append(block);
        for (int i = endLine + 1; i < lines.length; i++) {
            sb.append(lines[i]);
            if (i < lines.length - 1) {
                sb.append("\n");
            }
        }
        return sb.toString();
    }
}
